#!/usr/bin/env python3
"""Writes FINALS.md + finals.json: the ONLY files other AIs may use without asking Chase.
Edit APPROVED / REJECTED_EXTRA below (and covers.json), then: python3 make_finals.py"""
import json
REL='https://github.com/Cryptouprise/revboo-library/releases/download/media-v1/'
PAGES='https://cryptouprise.github.io/revboo-library/'
m=json.load(open('manifest.json')); cv=json.load(open('covers.json'))['covers']
F={f['id']:f for f in m['finals']}
FURNACE_NOTE=("Correct final ends with \"...your ads can't afford to miss.\" The original Seedance VO said \"abs\"; "
  "the last word was audio-patched to \"ads\" (same voice, taken from 0:02). Whisper large-v3/medium.en/small.en now hear "
  "\"your ads can't afford to miss\" (p 0.995/0.977/0.984). APPROVED by Chase on Oct 4, 2026 (\"perfect\"), including the patched \"ads\" word.")
APPROVED=[  # (id, master asset, role, extra note)
 ('furnace-captioned-9x16-v1','furnace-captioned-9x16-v1-MASTER.mp4','MAIN cut: Reels/TikTok/Shorts/Stories',
  'Style C captions (Inter Tight ExtraBold, white + one orange #FF4B0A word), placed off his face/torso. +2.5 s end-card hold with sound-off line "Get more out of your ad budget." -14 LUFS.'),
 ('furnace-captioned-4x5-v1','furnace-captioned-4x5-v1-MASTER.mp4','Feed cut (FB/IG feed)',
  'Per-shot reframe of the main cut; captions re-placed for 4:5.'),
 ('furnace-captioned-9x16-hookcover-v1','furnace-captioned-9x16-hookcover-v1-MASTER.mp4','TEST variant: A/B against the main cut',
  '1.25 s opening cover "Your ads are dying. Not the offer. The creative." (Muse thumbnail 01 line), then the main cut. Not a replacement.'),
]
NEWHAT_NOTE=("Built from the clean Higgsfield take hf_20260928_033156 (the latest take, and the picture under Chase's hook_A upload, without hook_A's "
  "burned-in all-caps hook). VO verified with Whisper small.en + large-v3 (word for word, no mispronunciations; 'Revboo' heard correctly). "
  "House caption standard (see BRAND.md); captions only where there is a clean zone. Shots that the cutout, the therapist or the title card fill have no caption. "
  "Light vignette/grain on scene shots only. -14 LUFS. PENDING: Chase to listen and OK.")
PENDING=[  # approved-pending-Chase-listen: (id, master asset, role, extra note)
 ('new-hat-captioned-9x16-v1','new-hat-captioned-9x16-v1-MASTER.mp4','MAIN cut: Reels/TikTok/Shorts/Stories',
  'Captions: "Your ad wants more." (wide shot, top band) / "Don\'t fire your media buyer." + "Give them better ads." (upper-left beside his head, 54 px) / end card "The revenue boost your ads can\'t afford to miss."'),
 ('new-hat-captioned-4x5-v1','new-hat-captioned-4x5-v1-MASTER.mp4','Feed cut (FB/IG feed)',
  'Per-shot reframe of the main cut; captions re-placed for 4:5.'),
]
REJECTED_EXTRA=[
 dict(id='(unfiled) hf_20260928_043047_01aeba6a',where='box: /workspace/revboo/inbox/higgsfield/_scan/vid/hf_20260928_043047_01aeba6a-4ac6-49d8-8537-322592a7d7c0.mp4',
      why='Sibling Furnace generation. Also says "abs" (Whisper medium.en p0.82-0.94) and the end card is garbled ("Donefor-youf"). Not in the library; do not use.'),
]
L=[]; a=L.append
a('# FINALS: approved Revboo assets\n')
a('> **Other AIs / editors: only use files listed under APPROVED below.** Everything else in the library is unreviewed (or rejected). Ask Chase before using it.')
a('> **Other AIs: follow [BRAND.md](BRAND.md) for all Revboo ads** (house caption standard, colors, fonts, covers, end card, audio, banned styles).')
a('> Shared catalog: Furnace = concept **RB-005**, New Hat = **RB-004** in `catalog/registry.json` (see [AGENTS.md](AGENTS.md)). RB-005 captioned cuts are **Approved** (Chase, Oct 4, 2026; `approved_asset_id` = furnace-captioned-9x16-v1). RB-004 captioned cuts are **Review** (approved-pending-Chase-listen).')
a(f'> Generated by `make_finals.py` from `manifest.json` + `covers.json`. Machine-readable copy: [`finals.json`](finals.json). Library page: {PAGES}\n')
a('## APPROVED videos (Chase approved)\n')
a('### Revboo Video Ad 1 (Furnace): "Furnace – Captioned Paid Ad"\n')
a('**Correct final VO (word for word):** "Before you throw more money at your ads, look at what you\'re feeding. Don\'t fire your media buyer. Give them better ads. Revboo, the revenue boost your **ads** can\'t afford to miss."\n')
a('> If a Furnace file ends with "your **abs**" or "your **apps** can\'t afford to miss", it is the BAD version. Do not use it.\n')
a('| Role | File | Size | Length | Full-quality master | Web copy (≤6 MB) |\n|---|---|---|---|---|---|')
out=dict(generated='Oct 4, 2026',rule='Only files listed here are approved. Everything else: ask Chase.',approved_videos=[],approved_covers=[],rejected=[])
for i,master,role,extra in APPROVED:
    f=F[i]; ar={(1080,1920):'9:16',(1080,1350):'4:5'}.get((f['width'],f['height']),f"{f['width']}x{f['height']}")
    a(f"| {role} | `{i}` | {f['width']}x{f['height']} ({ar}) | {f['duration']:.1f} s | [download]({REL}{master}) | [download]({f['video']}) |")
    out['approved_videos'].append(dict(id=i,title=f['title'],brand=f['brand'],version=f['version'],role=role,aspect=ar,
        width=f['width'],height=f['height'],duration=f['duration'],date=f['date'],master_url=REL+master,web_url=f['video'],
        local_master=f.get('source'),poster=PAGES+f['poster'],note=FURNACE_NOTE+' '+extra))
a('')
for i,master,role,extra in APPROVED: a(f"- `{i}`: {extra}")
a(f"\n**Notes:** {FURNACE_NOTE}  \nDate: Oct 4, 2026. Box masters: `/workspace/revboo/edits/fire-money-captioned/Revboo-Furnace-Captioned-*.mp4`.\n")
a('## APPROVED – PENDING CHASE LISTEN\n')
a('> Built to the house standard and machine-checked, but **Chase has not listened yet**. Usable for review/testing; get Chase\'s OK before spending on them.\n')
a('### A New Hat Isn\'t New Creative (cutout couples therapy): "A New Hat Isn\'t New Creative – Captioned Paid Ad"\n')
a('**VO (word for word, verified):** "Your ad wants more. You give it. Again. What\'s missing from this relationship? More budget. Have you tried being interesting? Don\'t fire your media buyer. Give them better ads. What about now? Revboo. The revenue boost your ads can\'t afford to miss."\n')
a('| Role | File | Size | Length | Full-quality master | Web copy (≤6 MB) |\n|---|---|---|---|---|---|')
out['pending_videos']=[]
for i,master,role,extra in PENDING:
    f=F[i]; ar={(1080,1920):'9:16',(1080,1350):'4:5'}.get((f['width'],f['height']),f"{f['width']}x{f['height']}")
    a(f"| {role} | `{i}` | {f['width']}x{f['height']} ({ar}) | {f['duration']:.1f} s | [download]({REL}{master}) | [download]({f['video']}) |")
    out['pending_videos'].append(dict(id=i,title=f['title'],brand=f['brand'],version=f['version'],role=role,aspect=ar,status='approved-pending-chase-listen',
        width=f['width'],height=f['height'],duration=f['duration'],date=f['date'],master_url=REL+master,web_url=f['video'],
        local_master=f.get('source'),poster=PAGES+f['poster'],note=NEWHAT_NOTE+' '+extra))
a('')
for i,master,role,extra in PENDING: a(f"- `{i}`: {extra}")
pc=[c for c in cv if c['status']=='pending']
if pc:
    a('\n**Covers (pending Chase):**\n')
    a('| Preview | File | For | Aspect | Line | Made by | Notes |\n|---|---|---|---|---|---|---|')
    out['pending_covers']=[]
    for c in pc:
        a(f"| <img src=\"{c['file']}\" width=\"110\"> | [`{c['file']}`]({c['file']}) | {c['for']} | {c['aspect']} ({c['size']}) | {c['line']} | {c['made_by']} | {c['note']} |")
        out['pending_covers'].append(dict(c,url=PAGES+c['file']))
a(f"\n**Notes:** {NEWHAT_NOTE}  \nOther takes: hf_20260928_032417 (earlier take, different line order) not used. Date: Oct 4, 2026. Box masters: `/workspace/revboo/edits/new-hat-captioned/Revboo-NewHat-Captioned-*.mp4`.\n")
a('## APPROVED cover / thumbnail assets (grouped with their ads)\n')
a('| Preview | File | For | Aspect | Line | Made by | Notes |\n|---|---|---|---|---|---|---|')
for c in cv:
    if c['status']!='approved': continue
    note=('⚠ **'+c['note']+'**') if c.get('warning') else c['note']
    a(f"| <img src=\"{c['file']}\" width=\"110\"> | [`{c['file']}`]({c['file']}) | {c['for']} | {c['aspect']} ({c['size']}) | {c['line']} | {c['made_by']} | {note} |")
    out['approved_covers'].append(dict(c,url=PAGES+c['file']))
a('\n> ⚠ **Muse #03 ($2,000 / month, 20 fresh video ads): Chase has NOT confirmed this pricing.** Don\'t publish it until he does.\n')
a('## REJECTED: do not use\n')
a('| File | Why |\n|---|---|')
for f in m['finals']:
    if f.get('status')=='rejected':
        a(f"| `{f['id']}` ({f['title']}, {f['version']}) | {f.get('note','')} |")
        out['rejected'].append(dict(id=f['id'],title=f['title'],version=f['version'],url=f['video'],source=f.get('source'),why=f.get('note','')))
for r in REJECTED_EXTRA:
    a(f"| `{r['id']}` ({r['where']}) | {r['why']} |"); out['rejected'].append(r)
a('\n## Everything else\n')
a(f"The other {len(m['finals'])-len(APPROVED)-len(PENDING)-sum(1 for f in m['finals'] if f.get('status')=='rejected')} finished ads and {len(m['clips'])} clips in the library are **not reviewed**. They may be old drafts. Ask Chase before using any of them.\n")
a('## Adding to this list\nOnly when Chase approves something: add it to `APPROVED` in `make_finals.py` (videos) or `covers.json` (images), run `python3 make_finals.py`, and commit.')
open('FINALS.md','w').write('\n'.join(L)+'\n'); json.dump(out,open('finals.json','w'),indent=1,ensure_ascii=False)
print('wrote FINALS.md, finals.json:',len(out['approved_videos']),'videos',len(out['approved_covers']),'covers',len(out['rejected']),'rejected')
