const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let assets=[],data=null,logs=[],selectedVersions=new Map(),playingId=null,editingId=null;
const amount=(x,money=false)=>x===null||x===undefined?'—':money?new Intl.NumberFormat('en-US',{style:'currency',currency:data?.currency||'USD',maximumFractionDigits:2}).format(x):new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(x);
const pct=x=>x===null?'—':(x*100).toFixed(1)+'%';
const empty=s=>'<div class="empty">'+esc(s)+'</div>';
function rows(){return (data?.rows||[]).filter(r=>(!$('account').value||r.account_id===$('account').value)&&(!$('from').value||r.date>=$('from').value)&&(!$('to').value||r.date<=$('to').value))}
function report(){const r=rows(),a=RevBooMetrics.aggregate(r,data?.crm_deduped===true);$('kpis').innerHTML=[['Media spend',amount(a.spend,true),'All selected stages'],['Qualified lead cost',amount(a.cpql,true),'Deduplicated CRM outcomes'],['Media CAC',amount(a.cac,true),'Includes audience-building spend'],['New customers',amount(a.new_customers),'Acquisition-date cohort']].map(([k,v,n])=>`<div class="kpi"><span>${k}</span><strong>${v}</strong><span>${n}</span></div>`).join('');
$('funnel').innerHTML=r.length?[['Impressions',a.impressions],['3-second views',a.views_3s],['ThruPlays',a.thruplays],['Outbound clicks',a.outbound_clicks],['Landing page views',a.landing_page_views],['Meta attributed leads (separate)',a.meta_leads],['CRM qualified leads',a.qualified_leads],['Booked calls',a.booked_calls],['Held calls',a.held_calls],['New customers',a.new_customers]].map(([k,v])=>`<div class="metric-row"><span>${k}</span><b>${amount(v)}</b></div>`).join(''):empty('Import Muse’s verified reporting to see the path from attention to customer. No sample performance is displayed.');
$('diagnostics').innerHTML=r.length?[['Hook · 3s views / impressions',pct(a.hook)],['Hold proxy · ThruPlay / 3s views',pct(a.hold)],['Outbound CTR',pct(a.ctr)],['Landing-page arrival rate',pct(a.arrival)],['Booked → held calls',pct(a.show)],['Held calls → customers',pct(a.close)],['Collected revenue / spend',a.cash_multiple===null?'—':a.cash_multiple.toFixed(2)+'×']].map(([k,v])=>`<div class="metric-row"><span>${k}</span><b>${v}</b></div>`).join('')+`<p class="small">CRM mature through: ${esc(data.crm_mature_through||'unknown')}. ${data.crm_deduped?'Importer reports CRM deduplication complete.':'CRM outcome metrics withheld: deduplication is not confirmed.'}</p>`:empty('Views tell us about attention. Qualified leads, held calls and customers tell us whether the attention is useful.');
const groups=new Map();r.forEach(x=>{let k=x.asset_id+'|'+x.strategy;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});$('economics').innerHTML=[...groups.values()].map(rs=>{let a=RevBooMetrics.aggregate(rs,data?.crm_deduped===true),source=assets.find(x=>x.id===rs[0].asset_id);return `<tr><td>${esc(source?.concept_id)} · ${esc(source?.title)}<br><small>${esc(rs[0].asset_id)}</small></td><td>${esc(rs[0].strategy)}</td><td>${amount(a.spend,true)}</td><td>${pct(a.hook)}</td><td>${amount(a.cpql,true)}</td><td>${amount(a.cac,true)}</td><td>${amount(a.new_customers)}</td><td>${esc([...new Set(rs.map(x=>x.operated_by))].join(', '))}</td></tr>`}).join('')||'<tr><td colspan="8">No reporting rows in this selection.</td></tr>';
$('strategy').innerHTML=['direct','sequence'].map(s=>{const ar=r.filter(x=>x.strategy===s),t=RevBooMetrics.aggregate(ar,data?.crm_deduped===true);return `<div class="metric-row"><span>${s==='direct'?'A / Direct':'B / Video + follow-up'}</span><span>Spend ${amount(t.spend,true)} · CPQL ${amount(t.cpql,true)} · CAC ${amount(t.cac,true)}</span></div>`}).join('');
$('status').textContent=data?`${r.length} selected daily rows · ${data.currency} · ${data.timezone} · Attribution: ${data.attribution} · Source updated: ${data.source_updated_at}`:`${assets.length} creative entries loaded · Awaiting metrics import · Accounts not connected`;}
function versionLabel(x){return (x.version||'Source clip')+' · '+x.id}
function groupedAssets(items,filters){
 const groups=new Map();
 items.forEach(x=>{const k=x.concept_id==='Unregistered'?x.id:x.concept_id;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});
 return [...groups.values()].filter(group=>group.some(x=>(!filters.collection||x.brand===filters.collection)&&(!filters.kind||x.kind===filters.kind)&&(!filters.agent||[x.created_by,x.last_edited_by,...x.agent_tags].includes(filters.agent))&&JSON.stringify([x.concept_id,x.id,x.title,x.aliases,x.note]).toLowerCase().includes(filters.q)));
}
function picked(group){return group.find(x=>x.id===selectedVersions.get(group[0].concept_id))||group.find(x=>x.id===x.approved_asset_id)||group[0]}
function library(){
 const filters={q:$('search').value.toLowerCase(),collection:$('collection').value,kind:$('kind').value,agent:$('agent').value};
 const groups=groupedAssets(assets,filters);
 $('creative-count').textContent=groups.length+' concepts · '+groups.reduce((n,g)=>n+g.length,0)+' versions together';
 $('cards').innerHTML=groups.map(group=>{const x=picked(group);return `<article class="creative">${x.poster?`<img loading="lazy" alt="${esc(x.title)}" src="https://cryptouprise.github.io/revboo-library/${esc(x.poster)}">`:''}<div class="eyebrow">${esc(x.concept_id)} · ${group.length} ${group.length===1?'VERSION':'VERSIONS'}</div><h3>${esc(x.concept_title||x.title)}</h3><label>Choose version<select data-version="${esc(x.concept_id)}">${group.map(v=>`<option value="${esc(v.id)}" ${v.id===x.id?'selected':''}>${esc(versionLabel(v))}</option>`).join('')}</select></label><div class="tags"><span>${esc(x.created_by)}</span><span>${esc(x.launch_status)}</span></div><p>${esc(x.note||'No source notes recorded.')}</p><p>Edited by ${esc(x.last_edited_by)} · ${esc(x.brand)}</p><div class="card-actions"><button data-play="${esc(x.id)}">Play version</button><button class="primary" data-edit="${esc(x.id)}">Request an edit</button></div><a href="${esc(x.video)}" target="_blank" rel="noopener">Selected MP4 ↗</a><details><summary>All versions & history (${group.length})</summary>${group.map(v=>`<div class="version-row"><b>${esc(v.version||'Source clip')}</b><p>${esc(v.id)}</p><p>${esc(v.note||'')}</p><button data-play="${esc(v.id)}">Play</button> <button data-edit="${esc(v.id)}">Edit this version</button><p>${esc(JSON.stringify(v.history))}</p></div>`).join('')}</details></article>`}).join('');
 document.querySelectorAll('[data-version]').forEach(sel=>sel.onchange=()=>{selectedVersions.set(sel.dataset.version,sel.value);library()});
 document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>playAsset(b.dataset.play));
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));
}
function playAsset(id){let a=assets.find(x=>x.id===id);if(!a)return;playingId=id;selectedVersions.set(a.concept_id,id);$('play-title').textContent=a.concept_id+' · '+a.title+' · '+(a.version||'Source clip');$('video').src=a.video;$('player').showModal();$('video').play().catch(()=>{})}
function timeLabel(s){if(!Number.isFinite(s))return '';const n=Math.floor(s);return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function editBrief(){const x=assets.find(a=>a.id===editingId);if(!x)return '';return [
 'REVBOO EDIT REQUEST',
 'Concept: '+x.concept_id+' — '+(x.concept_title||x.title),
 'Version: '+(x.version||'Source clip'),
 'Exact source asset: '+x.id,
 'Video: '+x.video,
 'Dashboard: https://cryptouprise.github.io/revboo-library/command.html?asset='+encodeURIComponent(x.id),
 'Timestamp / range: '+($('edit-time').value.trim()||'Whole video'),
 'Change: '+($('edit-change').value.trim()||'[Describe the change]'),
 'Keep: '+($('edit-keep').value.trim()||'Everything else unchanged.'),
 'Create a new revision under this concept. Preserve this source and previous versions. Read the shared workflow, verify the source, and return the new exact version plus a playable link.',
 'Workflow: https://github.com/Cryptouprise/revboo-library/blob/main/docs/AGENT_WORKFLOW.md'
 ].join('\n')}
function updateBrief(){$('edit-brief').value=editBrief();$('copy-state').textContent=''}
function openEdit(id,time=''){const x=assets.find(a=>a.id===id);if(!x)return;editingId=id;$('edit-title').textContent='Edit '+x.concept_id+' · '+(x.version||'Source clip');$('edit-source').textContent=x.id;$('edit-time').value=time;$('edit-change').value='';$('edit-keep').value='Everything else unchanged.';updateBrief();$('editor').showModal()}
function download(o,name){let b=new Blob([JSON.stringify(o,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function logRender(){$('logs').innerHTML=logs.map(l=>`<div class="log"><b>${esc(l.agent)} · ${esc(l.action)} · ${esc(l.asset_id)}</b><p>${esc(l.note)}</p><small>${esc(l.at)}</small></div>`).join('')}
async function boot(){try{const [m,g]=window.REVBOO_BOOTSTRAP?[window.REVBOO_BOOTSTRAP.manifest,window.REVBOO_BOOTSTRAP.registry]:await Promise.all(['manifest.json','catalog/registry.json'].map(x=>fetch(x).then(r=>{if(!r.ok)throw Error('Could not load '+x);return r.json()})));const refs=new Map();g.concepts.forEach(c=>c.assets.forEach(id=>refs.set(id,c)));assets=[...m.finals.map(x=>({...x,kind:'ad'})),...m.clips.map(x=>({...x,kind:'clip',title:x.name}))].map(x=>{let c=refs.get(x.id)||{},r=g.revision_records[x.id]||{};return {...x,concept_id:c.concept_id||'Unregistered',concept_title:c.title,approved_asset_id:c.approved_asset_id,aliases:c.aliases||[],created_by:r.created_by||c.created_by||'Unknown',last_edited_by:r.last_edited_by||c.last_edited_by||'Unknown',agent_tags:r.agent_tags||c.agent_tags||[],history:r.history||c.history||[],launch_status:r.status||'Review not verified'}});
for(const [id,values] of [['collection',[...new Set(assets.map(x=>x.brand))]],['agent',[...new Set(['ChatGPT','Claude','Grok','Muse','Human','Unknown',...assets.flatMap(x=>[x.created_by,x.last_edited_by,...x.agent_tags])])]]])values.sort().forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$(id).append(o)});$('collection').value='Revboo';const linked=assets.find(x=>x.id===new URLSearchParams(location.search).get('asset'));if(linked){selectedVersions.set(linked.concept_id,linked.id);$('collection').value='';$('search').value=linked.concept_id;document.querySelector('[data-tab=creative]').click()}library();report();}catch(e){$('error').textContent=e.message;$('status').textContent='Creative registry unavailable; no metrics loaded.'}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(s=>s.hidden=s.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b))});
['account','from','to'].forEach(id=>$(id).oninput=report);['search','collection','kind','agent'].forEach(id=>$(id).oninput=library);$('reset').onclick=()=>{['account','from','to'].forEach(id=>$(id).value='');report()};
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>10*1024*1024)throw Error('Limit this import to 10 MB.');let raw=JSON.parse(await f.text());const envelope=Object.prototype.hasOwnProperty.call(raw,'metrics')?raw:null;const candidate=envelope&&envelope.metrics===null?null:RevBooMetrics.validate(envelope?envelope.metrics:raw,new Set(assets.map(a=>a.id)));data=candidate;logs=envelope&&Array.isArray(envelope.decision_log)?envelope.decision_log:[];$('error').textContent='';$('account').innerHTML='<option value="">All imported accounts</option>';[...new Set((data?.rows||[]).map(r=>r.account_id))].forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$('account').append(o)});report();logRender();}catch(err){$('error').textContent='Import rejected: '+err.message}};
$('export').onclick=()=>{download({metrics:data,decision_log:logs},'RevBoo-private-reporting.json')};
$('decision').onsubmit=e=>{e.preventDefault();const aid=$('log-asset').value.trim();if(!assets.some(a=>a.id===aid)){$('error').textContent='Use an exact registered export ID in the decision log.';return}logs.unshift({at:new Date().toISOString(),agent:$('log-agent').value.trim(),asset_id:aid,action:$('log-action').value,note:$('log-note').value});$('log-note').value='';$('error').textContent='';logRender()};$('close').onclick=()=>{$('video').pause();$('player').close()};$('player').onclose=()=>{$('video').pause();$('video').removeAttribute('src')};boot();

$('template').onclick=()=>download({schema_version:1,currency:'USD',timezone:'SET_ACTUAL_TIMEZONE',attribution:'SET_ACTUAL_ATTRIBUTION',imported_at:null,source_updated_at:null,crm_mature_through:null,crm_deduped:false,rows:[]},'RevBoo-metrics-template.json');

$('edit-playing').onclick=()=>{const time=timeLabel($('video').currentTime);$('video').pause();$('player').close();openEdit(playingId,time)};
['edit-time','edit-change','edit-keep'].forEach(id=>$(id).oninput=updateBrief);
$('edit-close').onclick=()=>$('editor').close();
$('copy-brief').onclick=async()=>{try{await navigator.clipboard.writeText(editBrief());$('copy-state').textContent='Copied. Paste this into ChatGPT, Claude, Grok, or your editing agent.'}catch(e){$('edit-brief').focus();$('edit-brief').select();$('copy-state').textContent='Select and copy the request below. Automatic clipboard access is unavailable.'}};
$('download-brief').onclick=()=>{const blob=new Blob([editBrief()],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=editingId+'-edit-request.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
